core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('clientes/', include('clientes.urls', namespace="clientes")),
    path('profissionais/', include('profissionais.urls', namespace="profissionais")),
]

profissionais/urls.py
from django.urls import path
from . import views

app_name = 'profissionais'

urlpatterns = [
    path('registro/profissional/', views.profissional_cadastro, name='profissional_cadastro'),
    path('registro/servico/', views.servico_cadastro, name='servico_cadastro'),
    path('agendar/', views.agenda_cadastro, name='agendar_agendamento'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_agendamento_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_agendamento_deletar'),
    path('minhas/agendamentos/', views.agenda_lista, name="agenda_lista"),
    path('admim/lista/profissionais/', views.profissional_lista, name="profissionais_lista"),
    path('admim/lista/servicos/', views.servico_lista, name="servico_lista")
    
]

profissionais/models.py
import datetime
from datetime import date
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.db.models.fields.related import ForeignKey

class Servico(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=200)
    
    def __str__(self):
        return f'{self.nome}'
    
class Profissional(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=200)
    email = models.EmailField(verbose_name="Email")
    cpf = models.CharField(verbose_name="CPF", max_length=200)
    phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message="O número precisa estar neste formato: \
                    '+99 99 9999-0000'.")

    telefone = models.CharField(verbose_name="Telefone",
                                validators=[phone_regex],
                                max_length=17, null=True, blank=True)
    servico = ForeignKey(Servico,
                               on_delete=models.CASCADE,
                               related_name='profissionais')
    
    def __str__(self):
        return f'{self.nome}'

def validar_dia(value):
    today = date.today()
    weekday = date.fromisoformat(f'{value}').weekday()
    tomorrow = datetime.date.today() + datetime.timedelta(days=1)
    aftertomorrow = datetime.date.today() + datetime.timedelta(days=2)

    if value < today :
        raise ValidationError('Agendamento pelo sistema somente 2 dias antes .')
    
    if value == today :
        raise ValidationError('Agendamento pelo sistema somente 2 dias antes .')

    if value == tomorrow:
        raise ValidationError('Agendamento pelo sistema somente 2 dias antes .')

    if value == aftertomorrow:
        raise ValidationError('Agendamento pelo sistema somente 2 dias antes .')
    


    if (weekday == 5) or (weekday == 6):
        raise ValidationError('Escolha um dia útil da semana.')


class Agenda(models.Model):
    profissional = ForeignKey(Profissional, on_delete=models.CASCADE, related_name='agenda')
    dia = models.DateField(help_text="Insira uma data para agenda", validators=[validar_dia])
    
    HORARIOS = (
        ("1", "07:00 ás 08:00"),
        ("2", "08:00 ás 09:00"),
        ("3", "09:00 ás 10:00"),
        ("4", "10:00 ás 11:00"),
        ("5", "11:00 ás 12:00"),
    )
    horario = models.CharField(max_length=10, choices=HORARIOS)
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name='Usuário', 
        on_delete=models.CASCADE
    )
    class Meta:
        unique_together = ('horario', 'dia')
        
    def __str__(self):
        return f'{self.dia.strftime("%b %d %Y")} - {self.get_horario_display()} - {self.profissional}'

profissionais/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Profissional, Agenda, Servico


class TestMixinIsAdmin(UserPassesTestMixin):
    def test_func(self):
        is_admin_or_is_staff = self.request.user.is_superuser or \
            self.request.user.is_staff
        return bool(is_admin_or_is_staff)

    def handle_no_permission(self):
        messages.error(
            self.request, "Você não tem permissões!"
        )
        return redirect("accounts:index")

class ProfissionalCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Profissional
    login_url = 'accounts:login'
    template_name = 'profissionais/cadastro.html'
    fields = ['nome', 'cpf', 'email', 'telefone', 'servico']
    success_url = reverse_lazy('profissionais:profissionais_lista')
    
class ProfissionalListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'profissionais/profissionais_list.html'

    def get_queryset(self):
        return Profissional.objects.all().order_by('-pk')
    
class ServicoCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Servico
    login_url = 'accounts:login'
    template_name = 'profissionais/cadastro.html'
    fields = ['nome',]
    success_url = reverse_lazy('profissionais:servico_lista')
    
class ServicoListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'profissionais/servico_list.html'

    def get_queryset(self):
        return Servico.objects.all().order_by('-pk')


class AgendaCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'profissionais/agenda_cadastro.html'
    fields = ['profissional', 'dia', 'horario']
    success_url = reverse_lazy('profissionais:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaUpdateView(LoginRequiredMixin, TestMixinIsAdmin, UpdateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'profissionais/agenda_cadastro.html'
    fields = ['profissional', 'dia', 'horario']
    success_url = reverse_lazy('profissionais:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaDeleteView(LoginRequiredMixin, TestMixinIsAdmin, DeleteView):
    model = Agenda
    success_url = reverse_lazy('profissionais:agenda_lista')
    template_name = 'form_delete.html'

    def get_success_url(self):
        messages.success(self.request, "Agendamento excluída com sucesso!")
        return reverse_lazy('profissionais:agenda_lista')


class AgendaListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'profissionais/agenda_list.html'

    def get_queryset(self):
        return Agenda.objects.filter().order_by('-pk')
    
profissional_cadastro = ProfissionalCreateView.as_view()
profissional_lista = ProfissionalListView.as_view()
servico_cadastro = ServicoCreateView.as_view()
servico_lista = ServicoListView.as_view()
agenda_cadastro = AgendaCreateView.as_view()
agenda_atualizar = AgendaUpdateView.as_view()
agenda_lista = AgendaListView.as_view()
agenda_deletar = AgendaDeleteView.as_view()

templates/profissionais/agenda_cadastro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Cadastro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Agendamento</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.profissional.errors %} has-error{% endif %}">
                  <label for="{{ form.profissional.auto_id }}" class="col-md-3 control-label">
                  Cliente</label>
                  <div class="col-md-9">
                    {% render_field form.profissional class="form-control" %}

                    {% for error in form.profissional.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.dia.errors %} has-error{% endif %}">
                  <label for="{{ form.dia.auto_ud }}" class="col-md-3 control-label">
                  {{ form.dia.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.dia type="date" class="form-control" placeholder="01/01/2022" %}
                    {% for error in form.dia.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.horario.errors %} has-error{% endif %}">
                  <label for="{{ form.horario.auto_id }}" class="col-md-3 control-label">
                  {{ form.horario.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.horario class="form-control" %}

                    {% for error in form.horario.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

templates/profissionais/agenda_list.html
{% extends "accounts/index.html" %}

{% block title %}
    Agendas
{% endblock %}

{% block accounts_container %}
<h2>Agendas Disponiveis</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Cliente
            </th>
            <th>
                Dia
            </th>
            <th>
                Horario
            </th>
            <th>
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        {% for agendamento in object_list %}
        <tr>
            <td>
                <a href=""># {{ agendamento.pk }}</a>
            </td>
            <td>
                {{ agendamento.profissional }}
            </td>
            <td>
                {{ agendamento.dia|date:"d/m/Y" }}
            </td>
            <td>
                {{ agendamento.get_horario_display }}
            </td>
            <td>
                <a href="{% url 'profissionais:agendar_agendamento_atualizar' agendamento.id %}" class="text-primary" style="padding-left: 10px; text-decoration: none;">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'profissionais:agendar_agendamento_deletar' agendamento.id %}" class="mr-1 text-danger" style="padding-left: 10px; text-decoration: none;">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/profissionais/cadastro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Cadastro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Cadastro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">
                  {{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

templates/profissionais/profissionais_list.html
{% extends "accounts/index.html" %}

{% block title %}
    Clientes
{% endblock %}

{% block accounts_container %}
<h2>Clientes</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nome
            </th>
            <th>
                E-mail
            </th>
            <th>
                CPF
            </th>
            <th>
                Servico
            </th>
            <th>
                Telefone
            </th>
        </tr>
    </thead>
    <tbody>
        {% for profissional in object_list %}
        <tr>
            <td>
                <a href=""># {{ profissional.pk }}</a>
            </td>
            <td>
                {{ profissional.nome }}
            </td>
            <td>
                {{ profissional.email }}
            </td>
            <td>
                {{ profissional.cpf }}
            </td>
            <td>
                {{ profissional.servico }}
            </td>
            <td>
                {{ profissional.telefone }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/profissionais/servico_list.html
{% extends "accounts/index.html" %}

{% block title %}
   Serviço
{% endblock %}

{% block accounts_container %}
<h2>Serviço</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nome
            </th>
        </tr>
    </thead>
    <tbody>
        {% for servico in object_list %}
        <tr>
            <td>
                <a href=""># {{ servico.pk }}</a>
            </td>
            <td>
                {{ servico.nome }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}